### ISSUE TITLE
Local API version 2 set position doesn't work

### ISSUE THREAD

**Issue by vBrolin** [ualex73/goslide-api#3]
Been troubleshooting issues with API version 2.

Not sure how to make good code out of this, but this seems to be the issue:

The new format requires data to be sent like this:

{
	"pos": 0
}

In API version 1 it was sent like this:

{"pos": 0}

New documentation describes it like this:
"{\n\t\"pos\": 0\n}"

Would be really glad if this could be addressed

**Comment by Coldrush** [comment]
@ualex73 thanks for all your support with this add-on until now. It has been part of my daily workflow since I'm a HA fan/user.

I'm having issues with my Slides since I updated HA to the latest version. I first tried using the Cloud API but my slides remain unavailable even after adding the - so far I know - correct polling intervals. I decided to switch to the Local API and my Slides became available in HA again.

I think I'm almost there now but I seem to have the same issue as @vBrolin above. Would appreciate if you could have a look.

**Comment by vBrolin** [comment]
Bumping this again.
@ualex73 if you would like to have a look at this, I would appreciate it endlessly :)

**Comment by fritsvp** [comment]
That is not it, @vBrolin.

- The code seems to do some kind of dryrun before sending any commands to the device (eg: open or close), expecting a 401, but that is not the behaviour I see from my SLIDE. I do not understand the reason of the extra call, and the call does to give me a 401.
- the "if not version 1" part of the code appears to be incomplete:
  - there is some hardcoded "version=1" in there
  - I just got my slide, and never worked with v1, also do not see how to identify v2, but local api currently does not seem to require any form of authentication, although the code seems to add auth in the local api-request. the v1 code does have a lot of auth-magic in there.

**Comment by ualex73** [comment]
@fritsvp the local api is broken, because Slide changed the firmware (thus API change). The v1 is the original behavior, this worked before. The v2 tried to work around the authentication change, but it still does not able to do everything to the slide as it should.
We need to wait until the Slide updates the local API to be useable again.

**Comment by fritsvp** [comment]
I locally managed to perform calls to open/close/getInfo: all seem to work fine, I did not test any other endpoints.
I should findout how I can make a pullrequest

**Comment by vBrolin** [comment]
Other commands such as Stop works fine, it's just setting the position that doesn't work, since it is expecting a 3 row instruction instead of it all in a since row.
I've tested sending commands to the Slide using both formats in Postman, and it works fine if I split it up to 3 rows, ergo the new API behavior. Line breaks is a must.
I'm fairly sure that's the only change needed, but I'm not sure how to format it in the API code, nor how to test it locally.

**Comment by ualex73** [comment]
If you can send me the updates files or a link to you GitHub, then I will try to include it in the new API version.

Required line breaks in json code seems to be a faulty implementation :-( It should not matter at all, if properly implemented.

**Comment by fritsvp** [comment]
I think I created a pull request now. Sorry if I made any mistakes, it's my first.

**Comment by ualex73** [comment]
It looks fine, so I merged it. I also uploaded the created package to pypi.

Can you modify your manifest.json, in and change it from:
  "requirements": ["goslide-api==0.6.6"],
to:
  "requirements": ["goslide-api==0.6.7"],

And see if it now works out of the box? Ifso, I will update the manifest.json in the custom slide.

**Comment by vBrolin** [comment]
I forgot about this, but this is still not working for me with local API, so I thougth I'd bump it again.
I've attached the API documentation Slide sent med
[Slide Local API.zip](https://github.com/ualex73/goslide-api/files/14608210/Slide.Local.API.zip)

As far as I can see, setpos has changed formating

			"name": "Slide.SetPos",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"type": "text",
						"value": "application/json"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"pos\": 0\n}"
				},
				"url": {
					"raw": "{{slide_ip}}/rpc/Slide.SetPos",
					"host": [
						"{{slide_ip}}"
					],
					"path": [
						"rpc",
						"Slide.SetPos"
					]
				},



It used to be "raw": "{"pos\": 0}"
Now its. "raw": "{\n\t\"pos\": 0\n}"
Which would explain why I can stop my curtains, since that command hasn't changed, but I can set the position.

**Comment by ualex73** [comment]
I believe this works fine in the latest API, please log a new ticket if it persists with additional information.
